import { TinyProductBase } from './tiny-product-base';

export interface TinyProductDetails extends TinyProductBase {
  descricao_complementar: string | null;
  produto_pai_id: number | null;
  produto_pai_sku: string | null;
  produto_pai_descricao: string | null;
  unidade_por_caixa: string | null;
  ncm: string | null;
  gtin: string | null;
  origem: string | null;
  garantia: string | null;
  observacoes: string | null;
  categoria_id: number | null;
  categoria_nome: string | null;
  categoria_caminho: string | null;
  marca_id: number | null;
  marca_nome: string | null;
  embalagem_id: number | null;
  embalagem_tipo: number | null;
  embalagem_descricao: string | null;
  largura: number | null;
  altura: number | null;
  comprimento: number | null;
  diametro: number | null;
  quantidade_volumes: number | null;
  preco_custo: number | null;
  preco_custo_medio: number | null;
  controlar_estoque: boolean | null;
  sob_encomenda: boolean | null;
  dias_preparacao: number | null;
  localizacao: string | null;
  seo_titulo: string | null;
  seo_descricao: string | null;
  seo_keywords: string[] | null;
  seo_link_video: string | null;
  seo_slug: string | null;
  gtin_embalagem: string | null;
  valor_ipi_fixo: number | null;
  classe_ipi: string | null;
}