// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sptrkzceogbuzlvcoptx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdHJremNlb2didXpsdmNvcHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMTY5ODcsImV4cCI6MjA1MDg5Mjk4N30.etkK4nBMRFZd5KvZK8kW6olzR8s2RjBjYHK8evpxnoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);